name: simple_dart_image_button
description: Image Button Component
version: 0.0.1
repository: https://github.com/simple-dart/image_button
platforms:
  web:

environment:
  sdk: '>=2.18.0 <3.0.0'


dependencies:
  simple_dart_image: ^0.0.1
  simple_dart_ui_core: ^0.0.2

